name: Preparant per producció
run-name: ${{ github.actor }} està pujant l'aplicació a PROD 🚀
on: [push]
jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenint el codi del respositori
        uses: actions/checkout@v4

      - name: Verificar variables de entorno
        run: |
          echo "PROD_USER: ${{ secrets.PROD_USER }}"
          echo "PROD_HOST: ${{ secrets.PROD_HOST }}"

      - name: scp a produccio
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem

          # Asegurarse de que la carpeta web exista
          mkdir -p ${{ github.workspace }}/web

          # Copiar el archivo index.html al directorio web
          cp ${{ github.workspace }}/index.html ${{ github.workspace }}/web/

          # Crear el archivo last_deploy.txt
          echo "Action desplegant a produccio" > ${{ github.workspace }}/web/last_deploy.txt
          date >> ${{ github.workspace }}/web/last_deploy.txt

          # Verificar que el archivo está presente en la carpeta web
          ls -la ${{ github.workspace }}/web

          # Realizar la transferencia SCP
          scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ~/prod_key.pem ${{ github.workspace }}/web/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a23agunovnov/web/a23agunovnov.daw.inspedralbes.cat/public_html/ghactions
          
      - run: echo "🍏 This job's status is ${{ job.status }}."
