name: Preparant per producció
run-name: ${{ github.actor }} està pujant l'aplicació a PROD (/dist) 🚀
on: [push]
jobs:
  Pujar-a-produccio-amb-SCP:
    runs-on: ubuntu-latest
    steps:
      - name: Obtenint el codi del respositori
        uses: actions/checkout@v4

      - name: Verificar variables de entorno
        run: |
          echo "PROD_USER: ${{ secrets.PROD_USER }}"
          echo "PROD_HOST: ${{ secrets.PROD_HOST }}"

      - name: scp a produccio
        run: |
          echo "${{ secrets.PROD_KEY }}" > ~/prod_key.pem
          chmod 600 ~/prod_key.pem
          cd ${{ github.workspace }}
          mkdir -p ./web
          npm run build
          cp ./proyecto-vue/dist/* ${{ github.workspace }}/web/
          echo "Action desplegant a produccio" > ./web/last_deploy.txt
          date >> ./web/last_deploy.txt
          scp -r -o stricthostkeychecking=no -o UserKnownHostsFile=/dev/null -i "~/prod_key.pem" ./web/* ${{ secrets.PROD_USER }}@${{ secrets.PROD_HOST }}:/home/a23agunovnov/web/a23agunovnov.daw.inspedralbes.cat/public_html/ghactionsdist
          
      - run: echo "🍏 This job's status is ${{ job.status }}."
